name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
 
trigger:
  batch: true
  branches:
    include:
      - master
 
# Don't run against PRs
pr: none
 
stages :
 
  - stage: deployBicep
    jobs:
      - job: "BicepConfigure"
        steps:
  
          - task: Bash@3
            displayName: 'Install Bicep and build template'
            inputs:
              targetType: inline
              script: |
                curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
                chmod +x ./bicep
                ./bicep build $(System.DefaultWorkingDirectory)/bicep-files/ipaas-infra.bicep
 
          - task: AzureCLI@2
            displayName: 'Validate template'
            inputs:
              azureSubscription: 'sp-bicep-deploy'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                #!/bin/bash
                az deployment group validate -f $(System.DefaultWorkingDirectory)/bicep-files/ipaas-infra.json -g rg-bicep-poc

          - task: AzureCLI@2
            displayName: 'Deploy template'
            inputs:
              azureSubscription: 'sp-bicep-deploy'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                #!/bin/bash
                az deployment group create -f $(System.DefaultWorkingDirectory)/bicep-files/ipaas-infra.json -g rg-bicep-poc

          - task: PowerShell@2
            displayNAme: 'Generat connections file'
            inputs:
              targetType: 'filePath'
              filePath: $(System.DefaultWorkingDirectory)/scripts/generate-connections.ps1
              arguments: >
                -resourceGroup rg-bicep-poc
                -outputLocation $(System.DefaultWorkingDirectory)/connections.json
