name: build-ipaas-template

on: [push]

jobs:
  run-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bicep Build
      uses: aliencube/bicep-build-actions@v0.1
      with:
        # List of .bicep files to build, delimited by a space. eg) file1 file2 file3 ...
        files: bicep-files/ipaas-infra 